#pragma once

#include <Profiling/Profiling.h>

#define PROFILING_CATEGORY_VULKAN_LOW_LEVEL "Vulkan"

DECLARE_MEMORY_PROFILING_COUNTER(MemoryCounter_Vulkan_AllocatedBuffers);
DECLARE_MEMORY_PROFILING_COUNTER(MemoryCounter_Vulkan_AllocatedHostVisibleBuffers);
DECLARE_MEMORY_PROFILING_COUNTER(MemoryCounter_Vulkan_AllocatedImages);

DECLARE_COUNTING_PROFILING_COUNTER(CountingCounter_Vulkan_Buffers);
DECLARE_COUNTING_PROFILING_COUNTER(CountingCounter_Vulkan_Images);
DECLARE_COUNTING_PROFILING_COUNTER(CountingCounter_Vulkan_Pipelines);
DECLARE_COUNTING_PROFILING_COUNTER(CountingCounter_Vulkan_PipelinesCompute);
DECLARE_COUNTING_PROFILING_COUNTER(CountingCounter_Vulkan_PipelinesGraphics);
DECLARE_COUNTING_PROFILING_COUNTER(CountingCounter_Vulkan_PipelinesRayTracing);
DECLARE_COUNTING_PROFILING_COUNTER(CountingCounter_Vulkan_PipelineLayouts);
DECLARE_COUNTING_PROFILING_COUNTER(CountingCounter_Vulkan_DescriptorSets);
DECLARE_COUNTING_PROFILING_COUNTER(CountingCounter_Vulkan_CommandBuffers);
DECLARE_COUNTING_PROFILING_COUNTER(CountingCounter_Vulkan_RenderPasses);
DECLARE_COUNTING_PROFILING_COUNTER(CountingCounter_Vulkan_Framebuffers);
DECLARE_COUNTING_PROFILING_COUNTER(CountingCounter_Vulkan_BLASes);
DECLARE_COUNTING_PROFILING_COUNTER(CountingCounter_Vulkan_TLASes);